package org.tabletest.reporter.formats;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.tabletest.junit.Description;
import org.tabletest.junit.TableTest;
import org.tabletest.reporter.junit.TableTestPublisher;
import org.tabletest.reporter.support.PublishedReport;
import org.tabletest.reporter.support.SampleRun;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The custom template rules, read off a real report of {@link CalendarSample} generated with a
 * template directory of one file.
 */
@DisplayName("Custom templates")
@Description("""
        A report is rendered by Pebble templates, and a project can supply its own: point the
        reporter at a template directory and the files in it are used in place of, or on top of,
        the built-in ones. The rules below are read off a report of one test class titled Calendar
        with one table titled Leap years — Year | Leap? over one row, 2004 | Yes — so a page is
        short enough to state whole.
        """)
class CustomTemplateTest {

    @TempDir
    Path workingDir;

    @DisplayName("Uses a template of your own when it is named for the page it renders")
    @Description("""
            The name says which page a template renders: table or index, then the format. A file
            with exactly that name replaces the built-in one; a file whose name ends in it is used
            just the same, which is the form to reach for when the template extends the built-in,
            since a template cannot extend itself. A name for a different page is left for that
            page. Every template of your own below holds the same two lines:

                # {{ title }}

                Written by hand.
            """)
    @TableTest("""
        Scenario                   | Template file   | Page?
        No template of your own    |                 | ['## Leap years', '', '| Year | Leap? |', '| --- | --- |', '| 2004 | Yes |']
        Named for the page         | table.md.peb    | ['# Leap years', 'Written by hand.']
        Named ending in the page   | my-table.md.peb | ['# Leap years', 'Written by hand.']
        Named for a different page | index.md.peb    | ['## Leap years', '', '| Year | Leap? |', '| --- | --- |', '| 2004 | Yes |']
        """)
    void usesATemplateNamedForThePageItRenders(String templateFile, List<String> page) {
        Path templates = templateFile == null
                ? null
                : templateDirectoryHolding(templateFile, "# {{ title }}\n\nWritten by hand.\n");

        assertThat(tablePageWith(templates, "markdown")).isEqualTo(page);
    }

    @DisplayName("Lets a template of your own extend a built-in one and fill its blocks")
    @Description("""
            Replacing a template means rewriting the page. Extending one means naming the built-in
            template and filling only the blocks it leaves open — frontMatter above the page, title
            in place of the generated heading, footer below it — so the table itself keeps being
            rendered by the reporter. A template that fills one block reads:

                {% extends "table.md.peb" %}
                {% block frontMatter %}
                …
                {% endblock %}
            """)
    @TableTest("""
        Scenario                    | Block       | Filled with                      | Page?
        Front matter above the page | frontMatter | ['---', 'layout: report', '---'] | ['---', 'layout: report', '---', '## Leap years', '', '| Year | Leap? |', '| --- | --- |', '| 2004 | Yes |']
        A heading of your own       | title       | ['# {{ title }} of note']        | ['# Leap years of note', '', '', '| Year | Leap? |', '| --- | --- |', '| 2004 | Yes |']
        A footer below the page     | footer      | ['', '_Generated by us_']        | ['## Leap years', '', '| Year | Leap? |', '| --- | --- |', '| 2004 | Yes |', '', '_Generated by us_']
        """)
    void fillsTheBlocksTheBuiltInTemplateLeaves(String block, List<String> filledWith, List<String> page) {
        Path templates = templateDirectoryHolding(
                "my-table.md.peb", extending("table.md.peb", block, String.join("\n", filledWith)));

        assertThat(tablePageWith(templates, "markdown")).isEqualTo(page);
    }

    @DisplayName("Leaves the same three blocks in every built-in template")
    @Description("""
            The blocks are not a property of one template: a table and an index leave the same
            three, in every format the reporter generates. The one template below is written once
            per format and page, filling all three, and lands in the same places each time. Its
            title block holds {{ title }} of note with no markup of its own, so the same line can
            be looked for whichever format the page is written in.
            """)
    @TableTest("""
        Scenario             | Format   | Page  | Opens with?                      | Titled?            | Ends with?
        A table in markdown  | markdown | table | ['---', 'layout: report', '---'] | Leap years of note | _Generated by us_
        A table in asciidoc  | asciidoc | table | ['---', 'layout: report', '---'] | Leap years of note | _Generated by us_
        An index in markdown | markdown | index | ['---', 'layout: report', '---'] | Calendar of note   | _Generated by us_
        An index in asciidoc | asciidoc | index | ['---', 'layout: report', '---'] | Calendar of note   | _Generated by us_
        """)
    void leavesTheSameThreeBlocksInEveryTemplate(
            String format, String page, List<String> opensWith, String titled, String endsWith) {
        String builtIn = page + "." + extensionOf(format) + ".peb";
        Path templates = templateDirectoryHolding("my-" + builtIn, extendingAllThreeBlocksOf(builtIn));

        List<String> lines = pageWith(templates, format, page.equals("index"));

        assertThat(lines.subList(0, opensWith.size())).isEqualTo(opensWith);
        assertThat(lines).contains(titled);
        assertThat(lines.getLast()).isEqualTo(endsWith);
    }

    private static String extensionOf(String format) {
        return format.equals("markdown") ? "md" : "adoc";
    }

    /** A template naming a built-in one and filling one of the blocks it leaves. */
    private static String extending(String builtInTemplate, String blockName, String filledWith) {
        return extendsLine(builtInTemplate) + block(blockName, filledWith);
    }

    /** The same, filling all three blocks the built-in templates leave. */
    private static String extendingAllThreeBlocksOf(String builtInTemplate) {
        return extendsLine(builtInTemplate)
                + block("frontMatter", "---\nlayout: report\n---")
                + block("title", "{{ title }} of note")
                + block("footer", "\n_Generated by us_");
    }

    private static String extendsLine(String builtInTemplate) {
        return "{%% extends \"%s\" %%}\n".formatted(builtInTemplate);
    }

    private static String block(String blockName, String filledWith) {
        return """
            {%% block %s %%}
            %s
            {%% endblock %%}
            """.formatted(blockName, filledWith);
    }

    private Path templateDirectoryHolding(String fileName, String content) {
        try {
            Path directory = Files.createTempDirectory(workingDir, "templates");
            Files.writeString(directory.resolve(fileName), content);
            return directory;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private List<String> tablePageWith(Path templates, String format) {
        return pageWith(templates, format, false);
    }

    private List<String> pageWith(Path templates, String format, boolean index) {
        return PublishedReport.pageLinesOf(
                SampleRun.outputFor(CalendarSample.class, workingDir), format, templates, index, workingDir);
    }

    /**
     * Run only through {@link SampleRun} — a static nested class is not picked up by the
     * surrounding test run, so it publishes no page of its own.
     */
    @DisplayName("Calendar")
    @ExtendWith(TableTestPublisher.class)
    static class CalendarSample {

        @DisplayName("Leap years")
        @TableTest("""
            Year | Leap?
            2004 | Yes
            """)
        void leapYears(int year, String leap) {
            assertThat(year % 4 == 0 ? "Yes" : "No").isEqualTo(leap);
        }
    }
}
