package io.github.nchaugen.tabletest.reporter;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

public class TemplateExtensionBlocksTest {

    @TempDir
    Path tempDir;

    // Tests for AsciiDoc table template with inheritance
    @Test
    void asciidoc_table_can_extend_and_override_frontMatter_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.adoc.peb" %}
            {% block frontMatter %}
            ---
            layout: test-report
            ---
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith("---\nlayout: test-report\n---");
        assertThat(rendered).contains("== ++Test Table++");
        assertThat(rendered).contains("[%header,cols=");
    }

    @Test
    void asciidoc_table_can_extend_and_override_title_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.adoc.peb" %}
            {% block title %}
            === {{ title }} (Custom Title)
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).contains("=== Test Table (Custom Title)");
        assertThat(rendered).doesNotContain("== ++Test Table++");
    }

    @Test
    void asciidoc_table_can_extend_and_override_footer_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.adoc.peb" %}
            {% block footer %}

            ---
            _Generated by TableTest Reporter_
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).endsWith("---\n_Generated by TableTest Reporter_\n");
    }

    @Test
    void asciidoc_table_can_extend_and_override_multiple_blocks() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.adoc.peb" %}
            {% block frontMatter %}
            :toc: left

            {% endblock %}
            {% block title %}
            = {{ title }}
            {% endblock %}
            {% block footer %}

            Last updated: 2025-01-15
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith(":toc: left");
        assertThat(rendered).contains("= Test Table");
        assertThat(rendered).endsWith("Last updated: 2025-01-15\n");
    }

    // Tests for Markdown table template with inheritance
    @Test
    void markdown_table_can_extend_and_override_frontMatter_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.md.peb" %}
            {% block frontMatter %}---
            layout: default
            title: {{ title }}
            ---

            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.md.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.MARKDOWN, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith("---\nlayout: default\ntitle: Test Table---");
        assertThat(rendered).contains("## Test Table");
    }

    @Test
    void markdown_table_can_extend_and_override_all_blocks() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "table.md.peb" %}
            {% block frontMatter %}---
            author: Test Team
            ---

            {% endblock %}
            {% block title %}
            # {{ title }} - Custom
            {% endblock %}
            {% block footer %}

            ---
            _End of report_
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-table.md.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.MARKDOWN, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith("---\nauthor: Test Team\n---");
        assertThat(rendered).contains("# Test Table - Custom");
        assertThat(rendered).endsWith("---\n_End of report_\n");
    }

    // Tests for AsciiDoc index template with inheritance
    @Test
    void asciidoc_index_can_extend_and_override_frontMatter_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "index.adoc.peb" %}
            {% block frontMatter %}
            :toc: left
            :toclevels: 3

            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-index.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderIndex(BuiltInFormat.ASCIIDOC, Map.of(
            "name", "Test Index",
            "contents", List.of()
        ));

        assertThat(rendered).startsWith(":toc: left\n:toclevels: 3");
        assertThat(rendered).contains("= ++Test Index++");
    }

    @Test
    void asciidoc_index_can_extend_and_override_all_blocks() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "index.adoc.peb" %}
            {% block frontMatter %}
            :icons: font

            {% endblock %}
            {% block title %}
            = {{ title ? title : name }} Index
            {% endblock %}
            {% block footer %}

            ---
            © 2025 Test Project
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-index.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderIndex(BuiltInFormat.ASCIIDOC, Map.of(
            "name", "Test Index",
            "contents", List.of()
        ));

        assertThat(rendered).startsWith(":icons: font");
        assertThat(rendered).contains("= Test Index Index");
        assertThat(rendered).endsWith("---\n© 2025 Test Project\n");
    }

    // Tests for Markdown index template with inheritance
    @Test
    void markdown_index_can_extend_and_override_frontMatter_block() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "index.md.peb" %}
            {% block frontMatter %}---
            layout: index
            ---

            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-index.md.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderIndex(BuiltInFormat.MARKDOWN, Map.of(
            "name", "Test Index",
            "contents", List.of()
        ));

        assertThat(rendered).startsWith("---\nlayout: index\n---");
        assertThat(rendered).contains("# Test Index");
    }

    @Test
    void markdown_index_can_extend_and_override_all_blocks() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            {% extends "index.md.peb" %}
            {% block frontMatter %}---
            nav_order: 1
            ---

            {% endblock %}
            {% block title %}
            # 📚 {{ title ? title : name }}
            {% endblock %}
            {% block footer %}

            [Home](/)
            {% endblock %}
            """;
        Files.writeString(customTemplateDir.resolve("custom-index.md.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderIndex(BuiltInFormat.MARKDOWN, Map.of(
            "name", "Test Index",
            "contents", List.of()
        ));

        assertThat(rendered).startsWith("---\nnav_order: 1\n---");
        assertThat(rendered).contains("# 📚 Test Index");
        assertThat(rendered).endsWith("[Home](/)\n");
    }

    // Tests for complete replacement (not using extends)
    @Test
    void asciidoc_table_can_be_completely_replaced() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            = CUSTOM TABLE
            This is a completely custom template that doesn't extend the built-in one.

            Title: {{ title }}
            """;
        Files.writeString(customTemplateDir.resolve("table.adoc.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith("= CUSTOM TABLE");
        assertThat(rendered).contains("Title: Test Table");
        assertThat(rendered).doesNotContain("[%header,cols=");
    }

    @Test
    void markdown_index_can_be_completely_replaced() throws IOException {
        Path customTemplateDir = tempDir.resolve("templates");
        Files.createDirectories(customTemplateDir);

        String customTemplate = """
            # Custom Index: {{ title ? title : name }}

            This replaces the built-in template entirely.
            """;
        Files.writeString(customTemplateDir.resolve("index.md.peb"), customTemplate);

        TemplateEngine engine = new TemplateEngine(customTemplateDir);
        String rendered = engine.renderIndex(BuiltInFormat.MARKDOWN, Map.of(
            "name", "Test Index",
            "contents", List.of()
        ));

        assertThat(rendered).contains("# Custom Index: Test Index");
        assertThat(rendered).contains("This replaces the built-in template entirely");
    }

    @Test
    void builtin_templates_have_empty_frontMatter_and_footer_blocks() {
        TemplateEngine engine = new TemplateEngine();

        String rendered = engine.renderTable(BuiltInFormat.ASCIIDOC, Map.of(
            "title", "Test Table",
            "headers", List.of(Map.of("value", "Col1")),
            "rows", List.of()
        ));

        assertThat(rendered).startsWith("== ++Test Table++");
        assertThat(rendered).doesNotContain("---");
    }
}
