#!/bin/bash

# Common functions for compatibility tests

# Validate that YAML files were generated
# Arguments:
#   $1 - YAML directory path
#   $2 - Minimum number of expected files (default: 2)
validate_yaml_files() {
    local yaml_dir=$1
    local min_files=${2:-2}

    if [ ! -d "$yaml_dir" ]; then
        echo "ERROR: YAML directory not found: $yaml_dir"
        exit 1
    fi

    local yaml_count=$(find "$yaml_dir" -name "TABLETEST-*.yaml" | wc -l | tr -d ' ')
    if [ "$yaml_count" -lt "$min_files" ]; then
        echo "ERROR: Expected at least $min_files YAML files, found $yaml_count"
        exit 1
    fi

    echo "Found $yaml_count YAML files"
}

# Validate that output documentation files were generated
# Arguments:
#   $1 - Output directory path
#   $2 - File pattern (e.g., "*.adoc" or "*.md")
#   $3 - File type description (e.g., "AsciiDoc" or "Markdown")
#   $4 - Minimum number of expected files (default: 1)
validate_output_files() {
    local output_dir=$1
    local file_pattern=$2
    local file_type=$3
    local min_files=${4:-1}

    if [ ! -d "$output_dir" ]; then
        echo "ERROR: Output directory not created: $output_dir"
        exit 1
    fi

    local file_count=$(find "$output_dir" -name "$file_pattern" | wc -l | tr -d ' ')
    if [ "$file_count" -lt "$min_files" ]; then
        echo "ERROR: No $file_type files generated"
        exit 1
    fi

    echo "Generated $file_count $file_type files"
}

# Validate that a tabletest-reporter.yaml sidecar was discovered and applied to the root index.
# Proves the whole spec-metadata surface end-to-end: the spec title and intro replace the leaked
# package name, an intermediate page is retitled (fixing the lowercase "subpackage" leak), and the
# declared feature reading order leads its otherwise-alphabetical siblings.
# Arguments:
#   $1 - Root index file path (e.g. target/generated-docs/tabletest/index.md)
#   $2 - Expected spec title (the H1 that replaces the leaked package name)
validate_spec_metadata() {
    local index_file=$1
    local expected_title=$2

    if [ ! -f "$index_file" ]; then
        echo "ERROR: Root index not found: $index_file"
        exit 1
    fi

    # Spec title from the sidecar replaces the leaked deepest-common-package name ("example").
    if ! head -n 1 "$index_file" | grep -qF "# $expected_title"; then
        echo "ERROR: Spec title not applied (expected '# $expected_title', got: $(head -n 1 "$index_file"))"
        exit 1
    fi
    if head -n 1 "$index_file" | grep -q "^# example$"; then
        echo "ERROR: Leaked package name '# example' still present in root index"
        exit 1
    fi

    # Intro paragraph rendered onto the root index.
    if ! grep -qF "Living documentation generated by tabletest-reporter" "$index_file"; then
        echo "ERROR: Spec intro not applied to root index"
        exit 1
    fi

    # Intermediate index page retitled, so the lowercase "subpackage" package segment no longer leaks.
    if ! grep -qF "Subpackage Feature" "$index_file"; then
        echo "ERROR: Intermediate page not retitled to 'Subpackage Feature'"
        exit 1
    fi

    # Declared feature leads its siblings: alphabetical order would put custom-expectation-pattern
    # first, so the first top-level entry being the declared subpackage proves the reading order.
    local first_feature=$(grep -oE '\[[^]]+\]\(\./[a-z-]+/index\.md\)' "$index_file" | head -n 1)
    if ! echo "$first_feature" | grep -q "Subpackage Feature"; then
        echo "ERROR: Declared feature order not applied (expected subpackage to lead, got: $first_feature)"
        exit 1
    fi

    echo "Verified spec metadata applied (title, intro, retitle, feature order)"
}

# Validate that the sidecar's publish section selected the published pages at report time.
# Proves the surface end-to-end: an excluded page takes its subtree with it, an included page
# survives below an excluded one (and keeps its feature page alive), and pages held back are
# neither written nor linked — none of it depending on how the suite was tagged or run.
# Arguments:
#   $1 - Generated documentation root (e.g. target/generated-docs/tabletest)
validate_publish_selection() {
    local docs_dir=$1

    # Excluded class page: its other tables are held back...
    for held_back in "multiple-tabletests/multiplication.md" "multiple-tabletests/subtraction.md"; do
        if [ -f "$docs_dir/$held_back" ]; then
            echo "ERROR: Excluded page was published: $held_back"
            exit 1
        fi
    done

    # ...while the re-admitted table publishes, keeping its feature page alive.
    if [ ! -f "$docs_dir/multiple-tabletests/addition.md" ]; then
        echo "ERROR: Included page below an excluded one was not published: multiple-tabletests/addition.md"
        exit 1
    fi
    if [ ! -f "$docs_dir/multiple-tabletests/index.md" ]; then
        echo "ERROR: Feature page of a re-admitted table was not published"
        exit 1
    fi

    # A held-back page is not linked from the feature index either.
    if grep -q "subtraction" "$docs_dir/multiple-tabletests/index.md"; then
        echo "ERROR: Excluded page still linked from multiple-tabletests/index.md"
        exit 1
    fi

    # An excluded feature page takes its whole subtree with it.
    if [ -d "$docs_dir/nested-test-classes/inner-tests" ]; then
        echo "ERROR: Excluded feature subtree was published: nested-test-classes/inner-tests"
        exit 1
    fi

    # Its sibling under the same feature is untouched.
    if [ ! -f "$docs_dir/nested-test-classes/outer-test.md" ]; then
        echo "ERROR: Sibling of an excluded page was not published: nested-test-classes/outer-test.md"
        exit 1
    fi

    echo "Verified publish selection applied (exclude, subtree, include override)"
}

# Validate that generated HTML pulls in nothing from outside its own output tree.
# The built-in HTML format inlines all CSS/JS; the sole permitted asset reference is the
# shared, root-relative search index (tabletest-search-index.js) written to the output root
# and linked from every page by a depth prefix (e.g. ../tabletest-search-index.js). Matches
# attribute references only, so escaped URLs appearing as ordinary cell text do not trip it.
# Arguments:
#   $1 - Output directory path
assert_self_contained_html() {
    local output_dir=$1

    # Genuinely external references: absolute/protocol-relative URLs, external stylesheets,
    # or CSS imports. None may appear in a self-contained report.
    local external=$(grep -rlE '(src|href)="(https?:)?//|<link |@import|url\(https?:' \
        --include='*.html' "$output_dir" 2>/dev/null)

    # Any <script src=> other than the shared search-index sibling is an external asset.
    local scripts=$(grep -rnE '<script[^>]*src=' --include='*.html' "$output_dir" 2>/dev/null \
        | grep -vE 'src="(\.\./)*tabletest-search-index\.js"')

    if [ -n "$external" ] || [ -n "$scripts" ]; then
        echo "ERROR: HTML output is not self-contained (external references found in):"
        [ -n "$external" ] && echo "$external"
        [ -n "$scripts" ] && echo "$scripts"
        exit 1
    fi

    echo "Verified HTML output is self-contained (only the shared search-index asset is referenced)"
}

# Find CLI jar dynamically (version-independent)
# Returns the path to the CLI jar or exits with error
find_cli_jar() {
    local cli_jar=$(find ../../tabletest-reporter-cli/target -maxdepth 1 -name "tabletest-reporter-cli-*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" 2>/dev/null | head -n 1)
    if [ -z "$cli_jar" ] || [ ! -f "$cli_jar" ]; then
        echo "ERROR: CLI jar not found in ../../tabletest-reporter-cli/target"
        exit 1
    fi
    echo "$cli_jar"
}

# Get Maven plugin version dynamically (version-independent)
# Returns the version string or exits with error
get_maven_plugin_version() {
    local plugin_jar=$(find ../../tabletest-reporter-maven-plugin/target -maxdepth 1 -name "tabletest-reporter-maven-plugin-*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" 2>/dev/null | head -n 1)
    if [ -z "$plugin_jar" ] || [ ! -f "$plugin_jar" ]; then
        echo "ERROR: Maven plugin jar not found in ../../tabletest-reporter-maven-plugin/target"
        exit 1
    fi
    # Extract version from filename: tabletest-reporter-maven-plugin-0.2.1-SNAPSHOT.jar -> 0.2.1-SNAPSHOT
    local version=$(basename "$plugin_jar" | sed 's/tabletest-reporter-maven-plugin-//' | sed 's/.jar$//')
    echo "$version"
}
