package org.tabletest.reporter.pages;

import org.jsoup.nodes.Document;
import org.junit.jupiter.api.DisplayName;
import org.tabletest.junit.Description;
import org.tabletest.junit.TableTest;
import org.tabletest.reporter.TemplateEngine;
import org.tabletest.reporter.support.HtmlValidator;

import java.util.HashMap;
import java.util.Map;
import java.util.function.BiFunction;

import static org.assertj.core.api.Assertions.assertThat;
import static org.tabletest.reporter.BuiltInFormat.HTML;

/**
 * Verifies the footer every HTML page ends with: who generated the report, and when.
 */
@DisplayName("Page footer")
public class HtmlFooterRenderingTest {

    private static final Map<String, Object> RUN_TIMESTAMP =
            Map.of("datetime", "2026-07-20T14:32:09Z", "label", "20 Jul 2026 14:32 UTC");

    @DisplayName("Records on every page when the report was generated")
    @Description("""
        The run timestamp tells a reader whether the published spec still tracks the code it was
        generated from. Every page kind therefore carries it: the per-table page, the index page,
        and the single-file report alike.

        The readable label is paired with a machine-readable attribute, so tooling can compare it
        against the source revision.
        """)
    @TableTest("""
        Scenario              | Page kind                   | Footer?                                                 | Timestamp attribute?
        Report states its age | {TABLE, INDEX, SINGLE_FILE} | Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC | "2026-07-20T14:32:09Z"
        """)
    void every_page_records_when_the_report_was_generated(HtmlPage pageKind, String footer, String timestampAttribute) {
        Document document = HtmlValidator.parse(pageKind.render(RUN_TIMESTAMP));

        assertThat(document.select("footer.doc-footer").text()).isEqualTo(footer);
        assertThat(document.select("footer.doc-footer time").attr("datetime")).isEqualTo(timestampAttribute);
    }

    @DisplayName("Falls back to plain attribution without a timestamp")
    @Description("""
        A context assembled without a timestamp still gets the attribution. It does not get a
        footer with a dangling separator. A custom renderer driving the templates directly is
        such a context.
        """)
    @TableTest("""
        Scenario                | Page kind                   | Footer?
        No timestamp in context | {TABLE, INDEX, SINGLE_FILE} | Generated by tabletest-reporter
        """)
    void falls_back_to_plain_attribution_without_a_timestamp(HtmlPage pageKind, String footer) {
        Document document = HtmlValidator.parse(pageKind.render(null));

        assertThat(document.select("footer.doc-footer").text()).isEqualTo(footer);
    }

    /** The three HTML documents the reporter can produce, each rendered from a minimal context. */
    enum HtmlPage {
        TABLE((engine, context) -> engine.renderTable(HTML, context)),
        INDEX((engine, context) -> engine.renderIndex(HTML, context)),
        SINGLE_FILE(TemplateEngine::renderSingle);

        private final BiFunction<TemplateEngine, Map<String, Object>, String> renderer;

        HtmlPage(BiFunction<TemplateEngine, Map<String, Object>, String> renderer) {
            this.renderer = renderer;
        }

        String render(Map<String, Object> runTimestamp) {
            Map<String, Object> context = new HashMap<>(Map.of("title", "Specification"));
            context.put("generatedAt", runTimestamp);
            return renderer.apply(new TemplateEngine(), context);
        }
    }
}
