package org.tabletest.reporter.pages;

import org.jsoup.nodes.Document;
import org.junit.jupiter.api.DisplayName;
import org.tabletest.junit.Description;
import org.tabletest.junit.TableTest;
import org.tabletest.junit.TypeConverter;
import org.tabletest.reporter.SiteLink;
import org.tabletest.reporter.TemplateEngine;
import org.tabletest.reporter.support.HtmlValidator;

import java.util.HashMap;
import java.util.Map;
import java.util.function.BiFunction;

import static org.assertj.core.api.Assertions.assertThat;
import static org.tabletest.reporter.BuiltInFormat.HTML;

/**
 * Verifies the footer every HTML page ends with: where the report lives, who generated it, and when.
 */
@DisplayName("Page footer")
public class HtmlFooterRenderingTest {

    private static final Map<String, Object> RUN_TIMESTAMP =
            Map.of("datetime", "2026-07-20T14:32:09Z", "label", "20 Jul 2026 14:32 UTC");

    @DisplayName("Records on every page when the report was generated")
    @Description("""
        The run timestamp tells a reader whether the published spec still tracks the code it was
        generated from. Every page kind therefore carries it: the per-table page, the index page,
        and the single-file report alike.

        The readable label is paired with a machine-readable attribute, so tooling can compare it
        against the source revision.
        """)
    @TableTest("""
        Scenario              | Page kind                   | Footer?                                                 | Timestamp attribute?
        Report states its age | {TABLE, INDEX, SINGLE_FILE} | Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC | "2026-07-20T14:32:09Z"
        """)
    void every_page_records_when_the_report_was_generated(HtmlPage pageKind, String footer, String timestampAttribute) {
        Document document = HtmlValidator.parse(pageKind.render(RUN_TIMESTAMP, SiteLink.NONE));

        assertThat(document.select("footer.doc-footer").text()).isEqualTo(footer);
        assertThat(document.select("footer.doc-footer time").attr("datetime")).isEqualTo(timestampAttribute);
    }

    @DisplayName("Falls back to plain attribution without a timestamp")
    @Description("""
        A context assembled without a timestamp still gets the attribution. It does not get a
        footer with a dangling separator. A custom renderer driving the templates directly is
        such a context.
        """)
    @TableTest("""
        Scenario                | Page kind                   | Footer?
        No timestamp in context | {TABLE, INDEX, SINGLE_FILE} | Generated by tabletest-reporter
        """)
    void falls_back_to_plain_attribution_without_a_timestamp(HtmlPage pageKind, String footer) {
        Document document = HtmlValidator.parse(pageKind.render(null, SiteLink.NONE));

        assertThat(document.select("footer.doc-footer").text()).isEqualTo(footer);
    }

    @DisplayName("Links back to the site that hosts the report")
    @Description("""
        Every other link a report holds is relative within its own tree. A reader who arrives from a
        site therefore has no way back once inside, which the link below is there to fix. It is
        declared in the site section of the tabletest-reporter.yaml sidecar file, and the report
        links nowhere until it is.

        The address reaches the page as it was written, so a report published under a path of the
        hosting site is reachable by a root-relative address as well as an absolute one.

        The footer is a block of its own in each of the three page templates. A template of yours
        can override that block and call the siteLink macro to place the same link elsewhere.
        """)
    @TableTest("""
        Scenario                         | Page kind                   | Site                                              | Footer?                                                                            | Link target?
        Site declared for the report     | {TABLE, INDEX, SINGLE_FILE} | [label: TableTest, url: 'https://tabletest.org/'] | ↑ TableTest · Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC              | https://tabletest.org/
        Site hosts the report below it   | TABLE                       | [label: TableTest, url: /spec/]                   | ↑ TableTest · Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC              | /spec/
        Address declared without a label | TABLE                       | [url: 'https://tabletest.org/']                   | ↑ https://tabletest.org/ · Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC | https://tabletest.org/
        No site declared                 | {TABLE, INDEX, SINGLE_FILE} |                                                   | Generated by tabletest-reporter · 20 Jul 2026 14:32 UTC                            | ''
        """)
    void links_back_to_the_site_that_hosts_the_report(
            HtmlPage pageKind, SiteLink site, String footer, String linkTarget) {
        Document document = HtmlValidator.parse(pageKind.render(RUN_TIMESTAMP, site));

        assertThat(document.select("footer.doc-footer").text()).isEqualTo(footer);
        assertThat(document.select("footer.doc-footer a").attr("href")).isEqualTo(linkTarget);
    }

    @TypeConverter
    public static SiteLink parseSiteLink(Map<String, String> site) {
        return new SiteLink(site.get("label"), site.get("url"));
    }

    /** The three HTML documents the reporter can produce, each rendered from a minimal context. */
    enum HtmlPage {
        TABLE((engine, context) -> engine.renderTable(HTML, context)),
        INDEX((engine, context) -> engine.renderIndex(HTML, context)),
        SINGLE_FILE(TemplateEngine::renderSingle);

        private final BiFunction<TemplateEngine, Map<String, Object>, String> renderer;

        HtmlPage(BiFunction<TemplateEngine, Map<String, Object>, String> renderer) {
            this.renderer = renderer;
        }

        String render(Map<String, Object> runTimestamp, SiteLink site) {
            Map<String, Object> context = new HashMap<>(Map.of("title", "Specification"));
            context.put("generatedAt", runTimestamp);
            context.put("site", site == null ? null : site.toMap());
            return renderer.apply(new TemplateEngine(), context);
        }
    }
}
